### ISSUE TITLE
https://pdsuwwz.github.io/hoc-element-table 的示例对应的代码能给分享不

### ISSUE THREAD

**Issue by knight0707** [pdsuwwz/hoc-element-table#11]

**Comment by pdsuwwz** [comment]
`README.md` 里的 `Example` 就是的，可以试试看  ~
https://github.com/pdsuwwz/hoc-element-table/blob/master/README.md

**Comment by zyzweb** [comment]
Example 中的 import TableChildrenA from "./table-children-a"; 对应的组件在哪里?还有live demo的项目源代码在哪里

**Comment by pdsuwwz** [comment]
> Example 中的 import TableChildrenA from "./table-children-a"; 对应的组件在哪里?还有live demo的项目源代码在哪里

1. TableChildrenA 其实就是为了用 `renderComponent` 而随便写的一个组件，你也可以自己实现；

2. live demo 你指的是 `gh-page` 的代码吧, 在这个分支里哈 [hoc-element-table](https://github.com/pdsuwwz/vue-cli-app/tree/pages-hoc-element-table)，可以参考下 ~
