### ISSUE TITLE
你好 请教下怎么给表格设置多选列

### ISSUE THREAD

**Issue by ywager** [pdsuwwz/hoc-element-table#67]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/17868062/206945764-6f4eedc8-57fb-496e-81e3-ed678c11e734.png">

**Comment by pdsuwwz** [comment]
您好，只需要加一个空的 `<el-table-column />` 即可实现，但这一部分我记得是需要提前内置到 template 模板中的，而不是动态配置出来的列，类似这种：
<img width="729" alt="image" src="https://user-images.githubusercontent.com/19891724/206954412-4af31154-d33b-4dff-a64d-8ea690cf4f76.png">

同时需要控制是否显示多选表头，并且需要将其多选的回调事件等方法也暴露到父组件中

这一部分源码中还未实现，如果着急用的话欢迎提交 PR 或 fork 该仓库自行实现 `@xxxx/table`

后续我也会抽空把这个问题修复或者您可以等下一个大版本，希望可以帮到你 😊
